extraSecretEnv:
    DB_HOST: postgre.tooling.services
    DB_PORT: "8635"
    DB_USER: superset
    DB_PASS: Super$et22!
    DB_NAME: superset


supersetNode:
        #  replicaCount: 3
  connections:
    # You need to change below configuration incase bringing own PostgresSQL instance and also set postgresql.enabled:false
    db_host: postgre.tooling.services
    db_port: "8635"
    db_user: superset
    db_pass: Super$et22!
    db_name: superset

    #supersetWorker:
        #  replicaCount: 3

bootstrapScript: |
  #!/bin/bash
  rm -rf /var/lib/apt/lists/* && \
  python3 -m pip install --upgrade pip \
  pip install \
    psycopg2-binary==2.9.1 \
    redis==3.5.3 \
    pystan==2.19.1.1 \
    holidays==0.14.2 \
    prophet && \
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi



configOverrides:
  my_override: |
    FEATURE_FLAGS = {
        "THUMBNAILS": True,
        "DASHBOARD_NATIVE_FILTERS": True,
        "DASHBOARD_CROSS_FILTERS": True,
        "ENABLE_EXPLORE_DRAG_AND_DROP": True
    }


postgresql:
  ##
  ## Use the PostgreSQL chart dependency.
  ## Set to false if bringing your own PostgreSQL.
  enabled: false
  postgresHost: postgre.tooling.services.
  service:
    port: 8635
  ## PostgreSQL User to create.
  postgresqlUsername: superset
  ##
  ## PostgreSQL Password for the new user.
  ## If not set, a random 10 characters password will be used.
  postgresqlPassword: Super$et22!
  ##
  ## PostgreSQL Database to create.
  postgresqlDatabase: superset

## Configuration values for the Redis dependency.
## ref: https://github.com/bitnami/charts/blob/master/bitnami/redis
## More documentation can be found here: https://artifacthub.io/packages/helm/bitnami/redis
redis:
  ##
  ## Use the redis chart dependency.
  ##
  ## If you are bringing your own redis, you can set the host in supersetNode.connections.redis_host
  ##
  ## Set to false if bringing your own redis.
  enabled: true
  ##
  ## Set architecture to standalone/replication
  architecture: replication
  ##
  ## Auth configuration:
  ##
  auth:
    ## Enable password authentication
    enabled: false
    ## The name of an existing secret that contains the redis password.
    existingSecret: ""
    ## Name of the key containing the secret.
    existingSecretKey: ""
    ## Redis password
    password: superset
  ##
  ## Master configuration
  ##
  master:
    ##
    ## Image configuration
    # image:
      ##
      ## docker registry secret names (list)
      # pullSecrets: nil
    ##
    ## Configure persistance
    persistence:
      ##
      ## Use a PVC to persist data.
      enabled: true
      ##
      ## Persistant class
      storageClass: csi-disk
      ##
      ## Access mode:
      accessModes:
      - ReadWriteOnce
